# CI / CD for the fsl/conda/installer project.
#
# Unit tests are run every time commits are
# pushed to any branch.
#
# Release jobs are run every time a new tag
# is added. Release jobs assume that they
# are running in an environment with a
# directory $FSLINSTALLER_DEPLOY_DIRECTORY
# into which the fslinstaller.py script can
# be copied.

stages:
  - test
  - release


# These variables should be set as CI/CD variables in
# the fsl/conda/installer project via the GitLab UI.
variables:

  # Directory in which new versions of the
  # installer script should be copied into.
  FSLINSTALLER_DEPLOY_DIRECTORY: "/"

  # GitLab API token with enough privileges to push a
  # branch to the fsl/conda/manifest repository, and open
  # a merge request.  Used by the update_manifest.py
  # script to update the FSL release manifest file when a
  # new fslinstaller version is tagged.
  FSL_CI_API_TOKEN: ""


.test-template:
  stage: test
  tags:
    - fsl-ci
    - docker
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - bash ./.ci/unit_tests.sh

test:py27:
  extends: .test-template
  image:    python:2.7

test:py33:
  extends: .test-template
  image:    python:3.3

test:py34:
  extends: .test-template
  image:    python:3.4

test:py35:
  extends: .test-template
  image:    python:3.5

test:py36:
  extends: .test-template
  image:    python:3.6

test:py37:
  extends: .test-template
  image:    python:3.7

test:py38:
  extends: .test-template
  image:    python:3.8

test:py39:
  extends: .test-template
  image:    python:3.9


release:
  image: python:3.9
  tags:
    - fsl-ci
    - fslconda-channel-host
  rules:
    - if: '$CI_COMMIT_TAG != null'
  script:
    - bash ./.ci/new_release.sh
