# CI / CD for the fsl/conda/installer project.
# Unit tests are run every time commits are
# pushed to the master branch

stages:
  - test

.test-template:
  stage: test
  tags:
    - fsl-ci
    - docker
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - pip install --upgrade pip setuptools wheel
    - pip install pytest coverage pytest-cov mock
    - pytest -v --cov=fslinstaller test

test:py27:
  extends: .test-template
  image:    python:2.7

test:py33:
  extends: .test-template
  image:    python:3.3

test:py34:
  extends: .test-template
  image:    python:3.4

test:py35:
  extends: .test-template
  image:    python:3.5

test:py36:
  extends: .test-template
  image:    python:3.6

test:py37:
  extends: .test-template
  image:    python:3.7

test:py38:
  extends: .test-template
  image:    python:3.8

test:py39:
  extends: .test-template
  image:    python:3.9